### ISSUE TITLE
Missing export command results in not all functions being available in the namespace.

### ISSUE THREAD

**Issue by jduprey** [thomsonreuters/oqad#1]
When documentation of functions were moved to a file an export command was also removed.  This results in not all functions being available in the namespace.

**Comment by jduprey** [comment]
This should be resolved now, @sameenashah. Can we close?

**Comment by ghost** [comment]
Yes please

**Comment by ghost** [comment]
Yes please

**Comment by jduprey** [comment]
Per @sameenashah 's commmit, https://github.com/thomsonreuters/oqad/commit/a2f174357076483950aba038e3be1db223a35065, I'm closing this issue.
